export const UPDATE_PW_SETTINGS = 'UPDATE_PW_SETTINGS';
export const CREATE_PASSWORD = 'CREATE_PASSWORD';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const RESET_PW_SETTINGS = 'RESET_PW_SETTINGS';
export const UPDATE_UI_SETTINGS = 'UPDATE_UI_SETTINGS';
export const RESET_UI_SETTINGS = 'RESET_UI_SETTINGS';
